package com.kd.example.springbootdemo.data.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.io.Serial;
import java.io.Serializable;
import java.util.Objects;
import java.util.UUID;


@Data
@DynamoDBTable(tableName = "Product")
public class Product {
    @DynamoDBHashKey(attributeName = "productId")
    @DynamoDBAutoGeneratedKey
    private String productId;

    @DynamoDBAttribute(attributeName = "title")
    private String title;

    @DynamoDBAttribute(attributeName = "price")
    private float price;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "category")
    private String category;

    @DynamoDBAttribute(attributeName = "image")
    private String image;

    @DynamoDBAttribute(attributeName = "rating_rate")
    private float ratingRate;

    @DynamoDBAttribute(attributeName = "rating_count")
    private int ratingCount;

}
